---
id: pushchain
name: Push Chain
summary: Initialize the Push Chain core library in Remix
level: 1
tags:
  - JS
  - Remix
  - PushChain
steps:
  - name: Welcome
    path: 0-welcome
  - name: UEA Origin Demo (Calling getOriginForUEA from Solidity)
    path: 1-contract-helpers-solidity
  - name: Contract Helpers: UEAFactory Lookups
    path: 2-contract-helpers-js
  - name: Universal Counter Example
    path: 3-universal-counter-solidity
  - name: Send Universal Transaction
    path: 4-send-universal-transaction
  - name: Conclusion
    path: 5-conclusion
